/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Quests;
import Model.Words;
import static View.Login.StopPoint;
import static View.Login.listSubject;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author linh
 */
public class ViewTest extends javax.swing.JFrame {
    ArrayList<Quests> list = new ArrayList<>();
    Random rd = new Random();
    int rdSubjects;
    int rdQuests;
    int rdLocationAns;
    int result = 0;
    int numberOfQuest = 1;
    int numberOfQuests = 10;// option
    /**
     * Creates new form ViewTest
     */
    public ViewTest() {
        initComponents();
        _initQuests();
        
    }
    
    void _initResult(){
        title.setText("Complete");
        ans1.setText("");
        ans2.setText("");
        ans3.setText("");
        ans4.setText("");
        if(result < numberOfQuests/3) quest.setText(result+"/"+numberOfQuests+" Co gang them nhieu nhe ");
            else if (result < numberOfQuests/2)  quest.setText(result+"/"+numberOfQuests+" tam on roi day.co 1 chut nua thoi ");
                else if (result < numberOfQuests - 2) quest.setText(result+"/"+numberOfQuests+" so Great!  "); 
                    else  quest.setText(result+"/"+numberOfQuests+" PERFECT!  "); 
        
        
        
    }
    
    int _rdom(){
        int rdom;
        do{
                rdom = rd.nextInt(list.size());
        }while(rdom == rdQuests);
        return rdom;
    }
    
    void _randomQuests(){
        rdSubjects = rd.nextInt(StopPoint)+1; //random tu - den diem dung
        list = listSubject.get(rdSubjects).listQuests;
        rdQuests = rd.nextInt(list.size());//random tu 0 den so phan tu trong subject dc random// cau hoi that
        rdLocationAns = rd.nextInt(4)+1;
    }
    
    void _initQuests(){
        _randomQuests();
        
        //set random answer
        {            
            ans1.setText(list.get(_rdom()).getAnswer());
            ans2.setText(list.get(_rdom()).getAnswer());
            ans3.setText(list.get(_rdom()).getAnswer());
            ans4.setText(list.get(_rdom()).getAnswer());
        }
        //set real answer
        switch (rdLocationAns) {
            case 1:
                ans1.setText(list.get(rdQuests).getAnswer());
                break;
            case 2:
                ans2.setText(list.get(rdQuests).getAnswer());
                break;
            case 3:
                ans3.setText(list.get(rdQuests).getAnswer());
                break;
            case 4:
                ans4.setText(list.get(rdQuests).getAnswer());
                break;
            
            default:
                throw new AssertionError();
        }
        quest.setText(list.get(rdQuests).getAsk());
        title.setText(numberOfQuest+".."+listSubject.get(rdSubjects).getName());
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quest = new javax.swing.JTextArea();
        title = new javax.swing.JLabel();
        ans1 = new javax.swing.JRadioButton();
        ans3 = new javax.swing.JRadioButton();
        ans2 = new javax.swing.JRadioButton();
        ans4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        choice = new javax.swing.JButton();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 300));

        quest.setEditable(false);
        quest.setColumns(20);
        quest.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        quest.setRows(5);
        quest.setText("quest");
        quest.setWrapStyleWord(true);
        quest.setAutoscrolls(false);
        jScrollPane1.setViewportView(quest);
        quest.getAccessibleContext().setAccessibleParent(jPanel1);

        title.setFont(new java.awt.Font("Goudy Stout", 2, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 51, 51));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("title");

        ans1.setBackground(new java.awt.Color(255, 255, 255));
        ans1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ans1.setText("quest 1");
        ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans1ActionPerformed(evt);
            }
        });

        ans3.setBackground(new java.awt.Color(255, 255, 255));
        ans3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ans3.setText("quest 2");
        ans3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans3ActionPerformed(evt);
            }
        });

        ans2.setBackground(new java.awt.Color(255, 255, 255));
        ans2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ans2.setText("quest 3");
        ans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans2ActionPerformed(evt);
            }
        });

        ans4.setBackground(new java.awt.Color(255, 255, 255));
        ans4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ans4.setText("quest 4");
        ans4.setVerifyInputWhenFocusTarget(false);
        ans4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans4ActionPerformed(evt);
            }
        });

        choice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        choice.setText("Choice");
        choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        next.setText("Next ");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(choice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ans3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ans1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ans4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ans2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ans1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ans2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ans3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ans4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(next, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(choice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ans3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans3ActionPerformed
        // TODO add your handling code here:
        _removeChoice();
        ans3.setSelected(true);
    }//GEN-LAST:event_ans3ActionPerformed

    private void ans4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans4ActionPerformed
        // TODO add your handling code here:
        _removeChoice();
        ans4.setSelected(true);
    }//GEN-LAST:event_ans4ActionPerformed

    private void ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans1ActionPerformed
        // TODO add your handling code here:
        _removeChoice();
        ans1.setSelected(true);
    }//GEN-LAST:event_ans1ActionPerformed

    private void ans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans2ActionPerformed
        // TODO add your handling code here:
        _removeChoice();
        ans2.setSelected(true);
    }//GEN-LAST:event_ans2ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:

            if (numberOfQuest == numberOfQuests) {
                super.dispose();
                ViewMain vm = new ViewMain();
                vm.setVisible(true);
                vm.setLocationRelativeTo(null);
            }
            if(rdLocationAns == _checkChoice()) result++;
            numberOfQuest++;
            if(numberOfQuest < numberOfQuests){
                _removeChoice();
                _initQuests();
            }
            else{
                _initResult();
            }
        
    }//GEN-LAST:event_nextActionPerformed

    private void choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceActionPerformed
        // TODO add your handling code here:
        
        if (_checkChoice() != 0) {
            if (numberOfQuest == numberOfQuests) {
                super.dispose();
                ViewMain vm = new ViewMain();
                vm.setVisible(true);
                vm.setLocationRelativeTo(null);
            }
            if(rdLocationAns == _checkChoice()) result++;
            numberOfQuest++;
            if(numberOfQuest < numberOfQuests){
                _initQuests();
            }
            else{
                _initResult();
            }
            _removeChoice();
        }
    }//GEN-LAST:event_choiceActionPerformed

    
    void _removeChoice(){
        ans1.setSelected(false);
        ans2.setSelected(false);
        ans3.setSelected(false);
        ans4.setSelected(false);
    }
    int _checkChoice(){
        if (ans1.isSelected()) {
            return 1;
        } 
        if (ans2.isSelected()) {
            return 2;
        }
        if (ans3.isSelected()) {
            return 3;
        }
        if (ans4.isSelected()) {
            return 4;
        }
        return 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ans1;
    private javax.swing.JRadioButton ans2;
    private javax.swing.JRadioButton ans3;
    private javax.swing.JRadioButton ans4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JButton choice;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next;
    private javax.swing.JTextArea quest;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
